id: PC0FD853E
initial_creation_type: input
source_metadata:
  title: Jātaka Series
  language: bo
  description: 'Texts related to tales of the Buddha''s previous lives (jātaka; skyes
    rabs):'
  volume:
    f0c26e48fff843278137556132408cb4:
      title: How Our Supreme Teacher Generated Bodhicitta and Other Topics
      parent: History
    87c1107563e14adb8e7602e44905dd9e:
      title: Verses on the Buddha's Previous Lives
      parent: Prayers
created_at: '2022-03-01T04:00:32.935214'
last_modified_at: '2022-03-01T04:00:32.935217'
statistics:
  total_words: 1784
  total_non_words: 155
quality:
  non_words_ratio: 0.09
